# Form implementation generated from reading ui file 'ui/autorization.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setStyleSheet("/* Общее оформление окна */\n"
"QDialog {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #d4e4ff, stop:1 #ffffff); /* Яркий градиент */\n"
"    border: none;\n"
"}\n"
"\n"
"/* Заголовки, такие как QLabel для разделов */\n"
"QLabel {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: #4a4a4a; /* Тёмно-серый текст */\n"
"    padding: 5px;\n"
"}\n"
"\n"
"#autoriz {\n"
"    text-align: center;       /* Выравнивание текста по горизонтали */\n"
"    vertical-align: middle;   /* Выравнивание текста по вертикали */\n"
"    font-size: 20px;          /* Размер шрифта */\n"
"}\n"
"/* Поля ввода */\n"
"QLineEdit {\n"
"    background-color: #ffffff; /* Белый фон */\n"
"    border: 2px solid #c4c4c4; /* Серые границы */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #98AFE1; /* Цвет акцента при фокусе */\n"
"}\n"
"\n"
"/* Кнопки */\n"
"QPushButton {\n"
"    background-color: #98AFE1; /* Цвет кнопок */\n"
"    color: white;             /* Белый текст */\n"
"    border: 2px solid #5c6e96; /* Цвет границы */\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    padding: 8px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5c6e96; /* Цвет кнопки при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4b587a; /* Цвет кнопки при нажатии */\n"
"}\n"
"\n"
"/* Текстовые поля и списки */\n"
"QTextEdit, QPlainTextEdit {\n"
"    background-color: #ffffff; /* Белый фон */\n"
"    border: 2px solid #c4c4c4; /* Границы */\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"QTextEdit:focus, QPlainTextEdit:focus {\n"
"    border-color: #98AFE1; /* Акцент при фокусе */\n"
"}\n"
"\n"
"/* Таблицы */\n"
"QTableWidget {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #c4c4c4;\n"
"    gridline-color: #e0e0e0;\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #98AFE1; /* Заголовки таблиц */\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    padding: 5px;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Вкладки */\n"
"/* Оформление панели вкладок */\n"
"QTabWidget::pane {\n"
"    border: 2px solid #7289bb; /* Граница панели вкладок */\n"
"    border-radius: 8px;\n"
"    background-color: #ffffff; /* Белый фон панели */\n"
"}\n"
"\n"
"/* Общий стиль вкладок */\n"
"QTabBar::tab {\n"
"    background-color: #f5f5f5; /* Светлый фон вкладок */\n"
"    border: 2px solid #dddddd; /* Граница вкладок */\n"
"    border-radius: 8px;        /* Скруглённые углы */\n"
"    padding: 10px 20px;        /* Внутренние отступы */\n"
"    margin: 2px;               /* Расстояние между вкладками */\n"
"    font-size: 14px;           /* Размер текста вкладок */\n"
"    color: #333333;            /* Цвет текста вкладок */\n"
"    transition: all 0.2s ease; /* Анимация для плавного перехода */\n"
"}\n"
"\n"
"/* Стиль выбранной вкладки */\n"
"QTabBar::tab:selected {\n"
"    background-color: #98AFE1; /* Акцентный цвет для активной вкладки */\n"
"    border: 2px solid #4b587a; /* Граница для активной вкладки */\n"
"    color: white;              /* Белый текст для активной вкладки */\n"
"    font-weight: bold;         /* Жирный текст */\n"
"    margin-bottom: 2px;       /* Соединение вкладки с панелью */\n"
"}\n"
"\n"
"/* Стиль вкладок при наведении */\n"
"QTabBar::tab:!selected:hover {\n"
"    background-color: #98AFE1; /* Светло-серый фон при наведении */\n"
"    border: 2px solid #98AFE1; /* Изменение цвета границы при наведении */\n"
"    color: #000000;            /* Чёрный текст */\n"
"}\n"
"\n"
"/* Неактивные вкладки */\n"
"QTabBar::tab:!selected {\n"
"    background-color: #D0D8FB; /* Стильный пастельный голубой фон */\n"
"    border: 2px solid  #ffffff; /* Светло-серая граница */\n"
"    color: #333333;            /* Тёмный текст для неактивных вкладок */\n"
"}\n"
"\n"
"/* Задать фиксированную ширину вкладок */\n"
"QTabBar::tab {\n"
"    width: 150px; /* Фиксированная ширина */\n"
"    height: 40px; /* Фиксированная высота */\n"
"}\n"
"\n"
"\n"
"/* Выпадающие списки */\n"
"QComboBox {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid #c4c4c4;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border-color: #98AFE1;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    background: #98AFE1;\n"
"    border-left: 1px solid #c4c4c4; /* Разделительная линия между текстом и стрелкой */\n"
"    width: 20px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(icons/arrow_down.png); /* Укажите свой путь к иконке */\n"
"    width: 14px;\n"
"    height: 14px;\n"
"}\n"
"\n"
"QComboBox::down-arrow:pressed {\n"
"    position: relative;\n"
"    top: 1px; /* Эффект нажатия */\n"
"}\n"
"\n"
"/* Прогресс-бар */\n"
"QProgressBar {\n"
"    border: 2px solid #c4c4c4;\n"
"    border-radius: 5px;\n"
"    background-color: #ffffff;\n"
"    text-align: center;\n"
"    font-size: 14px;\n"
"    color: #4a4a4a;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #7289bb; /* Акцентный цвет заполнения */\n"
"    width: 20px;\n"
"}\n"
"\n"
"/* Базовый стиль чекбокса */\n"
"QCheckBox {\n"
"    spacing: 8px; /* Расстояние между квадратом и текстом */\n"
"    font-size: 14px;\n"
"    color: #4A4A4A; /* Темно-серый текст */\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Чекбокс в состоянии фокуса */\n"
"QCheckBox:focus {\n"
"    outline: none; /* Убираем стандартную рамку */\n"
"    color: #1E90FF; /* Синий текст при фокусе */\n"
"}\n"
"\n"
"/* Состояние чекбокса, когда он выбран */\n"
"QCheckBox::indicator:checked {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"}\n"
"\n"
"\n"
"/* Состояние чекбокса, когда он не выбран */\n"
"QCheckBox::indicator:unchecked {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 4px;\n"
"    background-color: #FFFFFF; /* Белый фон */\n"
"    border: 2px solid #C0C0C0; /* Серые границы */\n"
"}\n"
"\n"
"/* Состояние чекбокса, когда он отключен */\n"
"QCheckBox::indicator:disabled {\n"
"    background-color: #E0E0E0; /* Светло-серый фон */\n"
"    border: 2px solid #C0C0C0; /* Серые границы */\n"
"}\n"
"\n"
"/* Состояние частично выбранного чекбокса (например, \"Выбрать всё\") */\n"
"QCheckBox::indicator:indeterminate {\n"
"    background-color: #FFD700; /* Золотой фон для промежуточного состояния */\n"
"    border: 2px solid #FFD700;\n"
"}\n"
"\n"
"\n"
"")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setGeometry(QtCore.QRect(50, 30, 331, 231))
        self.frame.setStyleSheet("/* Стиль для QFrame с рамкой */\n"
"#frame {\n"
"    border: 2px solid rgba(76, 76, 76, 0.5);  /* Рамка только для QFrame */\n"
"    border-radius: 10px;         /* Скругленные углы */\n"
"    \n"
"}\n"
"\n"
"\n"
"\n"
"Line {\n"
"                 /* Убираем рамки у горизонтальных и вертикальных лэйаутов */\n"
"   color: rgba(76, 76, 76, 0.5); \n"
"\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.autoriz = QtWidgets.QLabel(parent=self.frame)
        self.autoriz.setGeometry(QtCore.QRect(100, 10, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        self.autoriz.setFont(font)
        self.autoriz.setStyleSheet("QLabel {\n"
"    text-align: center;       /* Выравнивание текста по горизонтали */\n"
"       vertical-align: middle;   /* Выравнивание текста по вертикали */\n"
"}")
        self.autoriz.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.autoriz.setScaledContents(True)
        self.autoriz.setObjectName("autoriz")
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(80, 24, 30, 34))
        self.label_4.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_4.setText("")
        self.label_4.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_4.setPixmap(QtGui.QPixmap("Design/icons/user.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.layoutWidget = QtWidgets.QWidget(parent=self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 70, 249, 150))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_2.setStyleSheet("Qlabel {\n"
"    border: none;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.line_2 = QtWidgets.QFrame(parent=self.layoutWidget)
        self.line_2.setStyleSheet("Line {\n"
"   color: rgba(76, 76, 76, 0.5); \n"
"}")
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.line = QtWidgets.QFrame(parent=self.layoutWidget)
        self.line.setStyleSheet("Line {\n"
"   color: rgba(76, 76, 76, 0.5); \n"
"}")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.pushButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    font-weight: bold;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Design/icons/in.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(285, 130, 41, 31))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background: transparent;\n"
"    icon: url(Design/icons/view.png); /* Иконка по умолчанию */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"    background: transparent;\n"
"    icon: url(icon/view_pressed.png); /* Иконка при нажатии */\n"
"}\n"
"\n"
"")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Design/icons/view.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.autoriz.setText(_translate("Dialog", "Авторизация"))
        self.label_2.setText(_translate("Dialog", "Логин"))
        self.label_3.setText(_translate("Dialog", "Пароль"))
        self.pushButton.setText(_translate("Dialog", "Войти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
